<Project>
  <PropertyGroup>
    <Authors>Thaylon Lopes</Authors>
    <Copyright>Copyright © 2026 Thaylon Lopes</Copyright>
    <PackageProjectUrl>https://github.com/thaylonlopes</PackageProjectUrl>
    <RepositoryUrl>https://github.com/thaylonlopes/TL.ResilientCore</RepositoryUrl>
  </PropertyGroup>
</Project>
