<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageType>Template</PackageType>
    <PackageVersion>1.3.1</PackageVersion>
    <PackageId>TL.ResilientCore.Template</PackageId>
    <Title>TL.ResilientCore Starter Kit</Title>
    <Authors>Thaylon Lopes</Authors>
    <Description>Template .NET corporativo com Clean Architecture, DDD, CQRS, Result Pattern, Outbox Pattern com Dead Letter Queue, Metapacotes TL.ExtensionLibrary v0.8.0, Central Package Management (CPM) e Testes de Carga k6.</Description>
    <PackageTags>dotnet-new;templates;clean-architecture;cqrs;outbox;ddd;testcontainers;mediatr;dead-letter-queue;k6;load-tests;metapackages;cpm</PackageTags>
    <TargetFramework>net9.0</TargetFramework>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <Copyright>Copyright © 2026 Thaylon Lopes</Copyright>
    
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!-- Inclusão explícita dos arquivos da solução + metadados de template .template.config + load-tests -->
    <Content Include=".template.config\**\*;src\**\*;tests\**\*;docs\**\*;load-tests\**\*;*.sln;docker-compose*.yml;Directory.Packages.props;Directory.Build.props;.github\**\*" 
             Exclude="**\bin\**;**\obj\**;**\*.user;**\artifacts\**;**\nupkg\**;**\load-tests\results\**" />
    <Compile Remove="**\*" />

    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="assets\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>