<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="TL.AuditLogger" />
    <PackageReference Include="TL.ClaimsPrincipalExtensionsLibrary" />
    <PackageReference Include="TL.HealthCheck" />
    <PackageReference Include="TL.MiddlewareLibrary" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\TL.ResilientCore.Application\TL.ResilientCore.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\TL.ResilientCore.Infrastructure\TL.ResilientCore.Infrastructure.csproj" />
  </ItemGroup>

</Project>
