<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\TL.ResilientCore.Domain\TL.ResilientCore.Domain.csproj" />
    <ProjectReference Include="..\..\src\Core\TL.ResilientCore.Application\TL.ResilientCore.Application.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\TL.ResilientCore.Infrastructure\TL.ResilientCore.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Presentation\TL.ResilientCore.Api\TL.ResilientCore.Api.csproj" />
  </ItemGroup>

</Project>
